[2024/07/23] Feature/marker/cu, rd >> Marker 기능 구현
BE-Friend-Develop-Team/detour pull request #18
Opened 2024-07-23 09:41 UTC by LeeNaYoung240

## #️⃣ 연관된 이슈

> #8, #9, #10, #11, #17 
> close #8 
> close #9
> close #10
> close # 11

## 📝 작업 내용

- Marker 생성
- Marker 글 작성
- Marker 글 수정
- Marker 전체 조회
- Marker 단건 조회
- Marker 삭제
- Marker Http 추가
- gitignore에 코드 추가

## 💬 리뷰 요구사항(선택)

> dailyPlan, Place 부분 구현이 되어있지 않아 연관된 부분 주석처리 후 TODO로 작성했습니다.
> Service 함수명 보시고 적절하지 않은 부분 알려주세요.

2024-07-23 11:48 UTC, LeeChangHyeong reviewed
코드 확인했습니다!
컨밴션 조금만 더 신경써 주세요!!

2024-07-23 11:48 UTC, LeeChangHyeong commented on http/http-client.private.env.json
> +    "ADMIN_TOKEN": "qlvmfpsemdpsmswjdakfajtwlrhrnldudns5auddmlroqkfwkrkdlTek"
P3 - 이 토큰은 숨길 수 있으면 숨겨서 올리는게 조금 더 좋을 것 같습니다! 숨길 수 있다면 수정 부탁드립니다~

2024-07-23 11:48 UTC, LeeChangHyeong commented on src/main/java/com/befriend/detour/domain/marker/dto/MarkerContentRequestDto.java
> +    @Getter
Q - Getter를 class위에 달지 않고 필드에 단 이유가 있을까요?

2024-07-23 11:48 UTC, LeeChangHyeong commented on src/main/java/com/befriend/detour/domain/marker/entity/MarkerStatusEnum.java
> +
P3 - 공백 한칸 삭제해주시면 컨벤션에 더 적합할 것 같네요!

2024-07-23 11:48 UTC, LeeChangHyeong commented on src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepository.java
> +
P3- 여기도 공백 있습니다!

2024-07-23 11:48 UTC, LeeChangHyeong commented on src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryCustom.java
> +    List<MarkerResponseDto> findByDailyPlanId(Long dailyPlanId);
P3 - 여기 위에도 한 칸 띄우시는게 컨벤션에 맞을 것 같아요

2024-07-23 11:48 UTC, LeeChangHyeong commented on src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryImpl.java
> +        return jpaQueryFactory.selectFrom(marker)
P3 - 여기 위에 띄우면 컨벤션에 더 맞을 것 같습니다~

2024-07-23 11:48 UTC, LeeChangHyeong commented on src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryImpl.java
> +                .fetchOne();
P3 - return 앞에 한칸 띄워주세요~

2024-07-23 11:56 UTC, sihyun615 requested changes
확인완료했습니다! 수고 많으셨어요☺️

2024-07-23 11:56 UTC, sihyun615 commented on src/main/java/com/befriend/detour/domain/marker/service/MarkerService.java
> +        validateActiveUser(user);
P2 - 차단된 사용자는 이렇게 메서드마다 추가하기보다 로그인하는 부분에서부터 막는게 좋지 않을까요?

2024-07-23 11:56 UTC, sihyun615 commented on src/main/java/com/befriend/detour/domain/marker/controller/MarkerController.java
> +    @PostMapping("/{dailPlanId}/markers/{placeId}")
P1 - dailyPlanId인데 오타난 것 같습니다!

2024-07-23 11:56 UTC, LeeNaYoung240 commented on http/http-client.private.env.json
> +    "ADMIN_TOKEN": "qlvmfpsemdpsmswjdakfajtwlrhrnldudns5auddmlroqkfwkrkdlTek"
삭제해서 수정했습니다!

2024-07-23 11:57 UTC, LeeNaYoung240 commented on src/main/java/com/befriend/detour/domain/marker/dto/MarkerContentRequestDto.java
> +    @Getter
잘못 달아서 class 위로 수정했습니다! 감사합니다

2024-07-23 11:57 UTC, LeeNaYoung240 commented on src/main/java/com/befriend/detour/domain/marker/entity/MarkerStatusEnum.java
> +
컨벤션에 맞게 수정했습니다!

2024-07-23 11:57 UTC, LeeNaYoung240 commented on src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepository.java
> +
컨벤션에 맞게 수정했습니다!

2024-07-23 11:57 UTC, LeeNaYoung240 commented on src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryCustom.java
> +    List<MarkerResponseDto> findByDailyPlanId(Long dailyPlanId);
컨벤션에 맞게 수정했습니다!

2024-07-23 11:58 UTC, LeeNaYoung240 commented on src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryImpl.java
> +        return jpaQueryFactory.selectFrom(marker)
컨벤션에 맞게 수정했습니다!

2024-07-23 11:58 UTC, LeeNaYoung240 commented on src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryImpl.java
> +                .fetchOne();
감사합니다! 컨벤션에 맞게 수정했습니다!

2024-07-23 12:00 UTC, LeeNaYoung240 commented on src/main/java/com/befriend/detour/domain/marker/controller/MarkerController.java
> +    @PostMapping("/{dailPlanId}/markers/{placeId}")
오타 수정했습니다! 감사합니다!

2024-07-24 01:36 UTC, LeeNaYoung240 commented on src/main/java/com/befriend/detour/domain/marker/service/MarkerService.java
> +        validateActiveUser(user);
네! 맞습니다. 로그인 하는 부분에서 막도록 수정했습니다!

2024-07-24 02:30 UTC, merged